services:
  avalanche:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
    image: avalanche-cli
    container_name: avalanche-cli-container
    restart: always
    volumes:
      - ./data:/root/.avalanche-cli
      - ./.env:/.env
      - ./start_network.sh:/start_network.sh
      - ./stop_network.sh:/stop_network.sh
      - ./deploy_myl1s.sh:/deploy_myl1s.sh
    ports:
      - "9650:9650"
      - "9651:9651"
      - "9652:9652"
      - "9653:9653"
      - "9750:9750"
    networks:
      default:
        ipv4_address: 172.0.0.3
    command: [ "bash", "-c", "while :; do sleep 10; done" ]

networks:
  default:
    ipam:
      config:
        - subnet: 172.0.0.0/24
